name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/action*/**'
      - '.github/action*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Update v1 tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -fa v1 -m "Update v1 tag to ${{ github.sha }}"
          git push origin v1 --force
